[build]
publish = "exampleSite/public"
command = "hugo --source exampleSite --config exampleSite/config.toml --themesDir ../.."

[context.production.environment]
HUGO_VERSION = "0.51"
HUGO_ENV = "production"