[build]
publish = "exampleSite/public"
command = "pwd && tree && hugo --source exampleSite --config exampleSite/config.toml --themesDir /opt/build --theme repo && tree"

[build.environment]
HUGO_VERSION = "0.51"