baseURL = "https://example.com"
languageCode = "en-us"
title = "Some Title"
theme = "minimal-bootstrap-hugo-theme"
enableGitInfo = false

[permalinks]
  post = "/:filename/"

[params]
  description = "Some description"
  navbarBackgroundColor = "#000"
  wrapperMaxWidth = "780px"
  customDateFormat = "Monday, January 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  googleAnalytics = "UA-123456789-1"

  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 2
  [[menu.nav]]
  name = "Some Page"
  url = "#"
  weight = 3